import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Fredoka } from "next/font/google";
import Navbar from "../layouts/navbar";
import "./globals.css";
import localFont from "next/font/local";

const sakurata = localFont({
  src: "../../public/assets/fonts/SAKURATA.otf", // or .otf, match the real extension
  variable: "--font-sakurata-face",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const googleSans = Montserrat({
  variable: "--font-google-sans",
  subsets: ["latin"]
})

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${fredoka.variable} ${sakurata.variable} ${googleSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}</body>
    </html>
  );
}
